site_name: Halooid Platform
site_description: Documentation for the Halooid multi-product platform
site_author: Halooid Team
site_url: https://yourusername.github.io/halooid

# Repository
repo_name: halooid
repo_url: https://github.com/yourusername/halooid
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Halooid

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
#  favicon: assets/favicon.png
#  logo: assets/logo.png

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: yourusername
      repo: halooid
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date


# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Architecture:
    - Overview: architecture/index.md
    - Backend: architecture/backend.md
    - Frontend: architecture/frontend.md
    - Mobile: architecture/mobile.md
    - Database: architecture/database.md
    - API: architecture/api.md
  - Products:
    - Overview: products/index.md
    - Taskake:
      - Overview: products/taskake/index.md
      - Features: products/taskake/features.md
      - API: products/taskake/api.md
      - User Guide: products/taskake/user-guide.md
    - Qultrix:
      - Overview: products/qultrix/index.md
      - Features: products/qultrix/features.md
      - API: products/qultrix/api.md
      - User Guide: products/qultrix/user-guide.md
    - AdminHub:
      - Overview: products/adminhub/index.md
      - Features: products/adminhub/features.md
      - API: products/adminhub/api.md
      - User Guide: products/adminhub/user-guide.md
    - CustomerConnect:
      - Overview: products/customerconnect/index.md
      - Features: products/customerconnect/features.md
      - API: products/customerconnect/api.md
      - User Guide: products/customerconnect/user-guide.md
    - Invantray:
      - Overview: products/invantray/index.md
      - Features: products/invantray/features.md
      - API: products/invantray/api.md
      - User Guide: products/invantray/user-guide.md
  - Development:
    - Overview: development/index.md
    - Setup: development/setup.md
    - Workflow: development/workflow.md
    - Coding Standards: development/coding-standards.md
    - Testing: development/testing.md
  - Deployment:
    - Overview: deployment/index.md
    - Backend: deployment/backend.md
    - Frontend: deployment/frontend.md
    - Mobile: deployment/mobile.md
  - API Reference:
    - Overview: api-reference/index.md
    - REST API: api-reference/rest.md
    - gRPC API: api-reference/grpc.md
  - Contributing:
    - Overview: contributing/index.md
    - Code of Conduct: contributing/code-of-conduct.md
    - Pull Requests: contributing/pull-requests.md
    - Issue Reporting: contributing/issue-reporting.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - Roadmap: roadmap.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/halooid
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
  version:
    provider: mike
    default: latest

extra_css:
  - assets/stylesheets/extra.css
