apiVersion: v1
kind: Namespace
metadata:
  name: halooid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: halooid-config
  namespace: halooid
data:
  db_host: "postgres"
  db_port: "5432"
  db_name: "halooid"
  redis_host: "redis"
  redis_port: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: halooid-secrets
  namespace: halooid
type: Opaque
data:
  # These are example values, replace with actual secrets in production
  # Values are base64 encoded
  db_user: aGFsb29pZA==  # halooid
  db_password: aGFsb29pZF9wYXNzd29yZA==  # halooid_password
  access_token_secret: eW91ci1hY2Nlc3MtdG9rZW4tc2VjcmV0  # your-access-token-secret
  refresh_token_secret: eW91ci1yZWZyZXNoLXRva2VuLXNlY3JldA==  # your-refresh-token-secret
